### ISSUE TITLE
Create Kraken Logo

### ISSUE THREAD

**Issue by paigerube14** [chaos-kubox/krkn#195]
Definitely want to try to add a cool logo for this project! This project has taken off some and getting traction so would be nice to have an official looking logo 

Maybe something like the below but tentacles around the kubernetes or OpenShift logo. Want to keep it fun with bright colors 
![image](https://user-images.githubusercontent.com/64206430/145097857-2f10567a-1414-4786-bc5d-99cbd21a2890.png)

**Comment by chaitanyaenr** [comment]
Huge +1, I love the idea of Kraken monster wrapping its tentacles around Kubernetes/OpenShift logo - very apt for the project's goal i.e to inject deliberate failures and find the areas to harden. 

Mary has designed pretty cool logs for multiple projects like Ceberus, Pbench etc. @maryshak1996 can we get some help with designing a logo for Kraken as well when you get time please?

**Comment by paigerube14** [comment]
Maybe using an image like this for the middle 
![image](https://user-images.githubusercontent.com/64206430/145100266-0857a135-af5d-466a-b098-18d9eabe9699.png)

**Comment by maryshak1996** [comment]
Hey there @Naga Ravi Chaitanya Elluri ***@***.***> I can
definitely work on getting this added into the visual design team queue :)
If you could capture this task in this form here
<https://docs.google.com/forms/d/e/1FAIpQLSdsEGZB8jVKx8fCigWM-2qlj4LwFmHCHhCxPCnQ5IzpE_ziRg/viewform>,
that would be great!

Mary Shakshober

Interaction / Visual Designer

***@***.*** ***@***.***> | 978.602.0969
<https://www.redhat.com/en>

**Comment by rpattath** [comment]
+1 for the logo and idea is awesome too.

**Comment by yogananth-subramanian** [comment]
Hi, we can combine all the three symbols chaos, kraken and  k8s.
based on wiki chaos sysmbol pops up this
[![image](https://user-images.githubusercontent.com/1875469/148012852-d2e1253e-0e2a-4fec-ac5b-22853cdc23ee.png)
](https://en.wikipedia.org/wiki/Symbol_of_Chaos#/media/File:Chaos-10202007.png)

which we could combine with below image
![image](https://user-images.githubusercontent.com/64206430/145100266-0857a135-af5d-466a-b098-18d9eabe9699.png)

Such that the spokes have that directional arrows like in the chaos symbol and instead of openshift, there would be the kraken.
